version.number=3.9.0-RC1-propensive
maven.version.number=3.9.0-RC1-propensive
copyright.string=Copyright 2002-2026, LAMP/EPFL
shell.banner=%n      ________ ___   / /  ___%n    / __/ __// _ | / /  / _ |%n  __\ \/ /__/ __ |/ /__/ __ |%n /____/\___/_/ |_/____/_/ | |%n                          |/  %s
