version.number=3.8.4
maven.version.number=3.8.4
copyright.string=Copyright 2002-2026, LAMP/EPFL
shell.banner=%n      ________ ___   / /  ___%n    / __/ __// _ | / /  / _ |%n  __\\ \\/ /__/ __ |/ /__/ __ |%n /____/\\___/_/ |_/____/_/ | |%n                          |/  %s
